url: "https://basavaprabhuani.github.io"

title: Basavaprabhu's Portfolio and Science Blog
email: basavaprabhu.ani@gmail.com

description: |
  Â© 2026 Basavaprabhu Ani

theme: minima
markdown: GFM

header_pages:
  - aboutme.md
  - projects.md
  - posts.md
  - bucket_list.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

github_username: basavaprabhuani
youtube_username: "@basavaprabhuani4113"

google_analytics: true
